"""
静态合约列表 - 当API无法获取时使用
"""

BINANCE_USDT_PERPETUALS = [
    # 主要合约 (80个)
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT",
    "ADAUSDT", "AVAXUSDT", "DOGEUSDT", "DOTUSDT", "MATICUSDT",
    "LINKUSDT", "UNIUSDT", "LTCUSDT", "ATOMUSDT", "ETCUSDT",
    "FILUSDT", "NEARUSDT", "ALGOUSDT", "VETUSDT", "ICPUSDT",
    "AAVEUSDT", "APEUSDT", "APTUSDT", "ARBUSDT", "AXSUSDT",
    "BCHUSDT", "BLURUSDT", "COMPUSDT", "CRVUSDT", "DASHUSDT",
    "EOSUSDT", "FETUSDT", "FLOWUSDT", "FTMUSDT", "GALAUSDT",
    "GRTUSDT", "HBARUSDT", "IMXUSDT", "INJUSDT", "KAVAUSDT",
    "KSMUSDT", "LDOUSDT", "LUNCUSDT", "MAGICUSDT", "MANAUSDT",
    "MASKUSDT", "MINAUSDT", "MKRUSDT", "OPUSDT", "PEPEUSDT",
    "RNDRUSDT", "RUNEUSDT", "SANDUSDT", "SEIUSDT", "SHIBUSDT",
    "SNXUSDT", "STGUSDT", "STXUSDT", "SUIUSDT", "THETAUSDT",
    "TRBUSDT", "TRXUSDT", "TWTUSDT", "UNFIUSDT", "WAVESUSDT",
    "WLDUSDT", "XLMUSDT", "XMRUSDT", "YFIUSDT", "ZECUSDT",
    "ZILUSDT", "ZRXUSDT", "1000SATSUSDT", "1000BONKUSDT", "1INCHUSDT",
    "AAVEUSDT", "ACHUSDT", "ACMUSDT", "ADXUSDT", "AGIXUSDT",
    "AGLDUSDT", "AKROUSDT", "ALICEUSDT", "ALPHAUSDT", "AMBUSDT",
]

OKX_USDT_SWAPS = [
    # 主要合约 (50个)
    "BTC-USDT-SWAP", "ETH-USDT-SWAP", "BNB-USDT-SWAP", "SOL-USDT-SWAP",
    "XRP-USDT-SWAP", "ADA-USDT-SWAP", "AVAX-USDT-SWAP", "DOGE-USDT-SWAP",
    "DOT-USDT-SWAP", "MATIC-USDT-SWAP", "LINK-USDT-SWAP", "UNI-USDT-SWAP",
    "LTC-USDT-SWAP", "ATOM-USDT-SWAP", "ETC-USDT-SWAP", "FIL-USDT-SWAP",
    "NEAR-USDT-SWAP", "ALGO-USDT-SWAP", "VET-USDT-SWAP", "ICP-USDT-SWAP",
    "AAVE-USDT-SWAP", "APE-USDT-SWAP", "APT-USDT-SWAP", "ARB-USDT-SWAP",
    "AXS-USDT-SWAP", "BCH-USDT-SWAP", "BLUR-USDT-SWAP", "COMP-USDT-SWAP",
    "CRV-USDT-SWAP", "DASH-USDT-SWAP", "EOS-USDT-SWAP", "FET-USDT-SWAP",
    "FLOW-USDT-SWAP", "FTM-USDT-SWAP", "GALA-USDT-SWAP", "GRT-USDT-SWAP",
    "HBAR-USDT-SWAP", "IMX-USDT-SWAP", "INJ-USDT-SWAP", "KAVA-USDT-SWAP",
    "KSM-USDT-SWAP", "LDO-USDT-SWAP", "LUNC-USDT-SWAP", "MAGIC-USDT-SWAP",
    "MANA-USDT-SWAP", "MASK-USDT-SWAP", "MINA-USDT-SWAP", "MKR-USDT-SWAP",
    "OP-USDT-SWAP", "PEPE-USDT-SWAP", "RNDR-USDT-SWAP",
]

# 导出字典
STATIC_SYMBOLS = {
    "binance": BINANCE_USDT_PERPETUALS,
    "okx": OKX_USDT_SWAPS
}